export async function GET() {
    try {
        const countries = [
            "USA",
            "Germany",
            "UK",
            "France",
            "Uzbekistan",
            "Japan",
            "South Korea",
            "India",
            "Italy",
            "Spain",
            "Russia",
            "Australia",
            "Canada",
            "Brazil",
            "Mexico",
            "China",
            "Turkey",
            "Netherlands",
            "Sweden",
            "Norway",
            "Denmark",
            "Finland",
            "Poland",
            "Czech Republic",
            "Hungary",
            "Greece",
            "Portugal",
            "Switzerland",
            "Austria",
            "Belgium",
            "Argentina",
            "Chile",
            "Colombia",
            "Peru",
            "Venezuela",
            "Egypt",
            "South Africa",
            "Nigeria",
            "Kenya",
            "Morocco",
            "England",
            "Ireland",
            "Scotland",
            "Wales",
            "New Zealand",
        ];
        return new Response(JSON.stringify({ countries }), { status: 200 });
    } catch (err) {
        return new Response(JSON.stringify({ error: err.message }), { status: 500 });
    }
}
